/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UILayer;

import BusinessLayer.Admin;
import BusinessLayer.IAdmin;
import BusinessLayer.IStaff;
import BusinessLayer.InputValidation;
import BusinessLayer.Staff;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Innes Herbst
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    private final Border tFieldBorder;
    private final Color cmbBorder;
    private final String[] campus = new String[]{"--Please Select--", "Pretoria", "Kempton", "Port Elizabeth"};
    private final String[] department = new String[]{"--Please Select--", "Programming", "Networking", "Information Systems"};
    private final String[] position = new String[]{"--Please Select--", "Staff Member", "Administrator"};
    private IStaff staff;
    private IAdmin admin;

    public RegistrationForm() throws RemoteException, NotBoundException {
        initComponents();
        Registry reg = LocateRegistry.getRegistry("localhost", 1099);
        staff = (IStaff) reg.lookup("StaffService");
        admin = (IAdmin) reg.lookup("AdminService");
        tFieldBorder = txtFirstName.getBorder();
        cmbBorder = cmbPosition.getBackground();

        //Set the date for DoB Picker
        SimpleDateFormat sdf = new SimpleDateFormat("dd, MMMM yyyy");
        Calendar calender = Calendar.getInstance();
        calender.add(Calendar.YEAR, -18);
        dpkDoB.setDate(calender.getTime());
        dpkDoB.getMonthView().setUpperBound(calender.getTime());
        calender.add(Calendar.YEAR, -82);
        dpkDoB.getMonthView().setLowerBound(calender.getTime());
        dpkDoB.setFormats(sdf);

        //Campus CMB
        cmbCampus.removeAllItems();
        cmbCampus.setModel(new DefaultComboBoxModel<>(campus));
        //Department CMB
        cmbDepartment.removeAllItems();
        cmbDepartment.setModel(new DefaultComboBoxModel<>(department));
        //Position CMB
        cmbPosition.removeAllItems();
        cmbPosition.setModel(new DefaultComboBoxModel<>(position));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpGender = new javax.swing.ButtonGroup();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        pnlRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtInitial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbnMale = new javax.swing.JRadioButton();
        rbnFemale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtCellNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSAddrress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbCampus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        cmbPosition = new javax.swing.JComboBox<>();
        chbShowPassword = new javax.swing.JCheckBox();
        dpkDoB = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setName("frmRegistration"); // NOI18N
        setResizable(false);

        pnlRegister.setBorder(javax.swing.BorderFactory.createTitledBorder("Register"));

        jLabel1.setText("First Name : ");

        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });

        jLabel2.setText("Initials : ");

        txtInitial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInitialFocusLost(evt);
            }
        });

        jLabel3.setText("ID : ");

        txtStaffID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStaffIDFocusLost(evt);
            }
        });

        jLabel4.setText("Last Name : ");

        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });

        jLabel5.setText("Date Of Birth : ");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        jLabel6.setText("Gender : ");

        bgpGender.add(rbnMale);
        rbnMale.setText("Male");

        bgpGender.add(rbnFemale);
        rbnFemale.setText("Female");

        jLabel7.setText("Cell : ");

        txtCellNum.setToolTipText("Cell Number");
        txtCellNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCellNumFocusLost(evt);
            }
        });

        jLabel8.setText("Email : ");

        txtEmail.setToolTipText("Email Address");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        jLabel9.setText("Address : ");

        txtSAddrress.setToolTipText("Street Address");
        txtSAddrress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSAddrressFocusLost(evt);
            }
        });

        jLabel10.setText("Campus : ");

        cmbCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCampus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbCampusFocusLost(evt);
            }
        });

        jLabel11.setText("Department : ");

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDepartment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbDepartmentFocusLost(evt);
            }
        });

        jLabel12.setText("Password : ");

        txtPassword.setToolTipText("Enter preffered password");
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        jLabel13.setText("Position : ");

        cmbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPosition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbPositionFocusLost(evt);
            }
        });

        chbShowPassword.setText("Show");
        chbShowPassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbShowPasswordItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCampus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPosition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDepartment, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegister))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCellNum))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtInitial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtStaffID, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                                .addComponent(rbnFemale)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbnMale))
                                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dpkDoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSAddrress, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chbShowPassword)))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dpkDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbnMale)
                    .addComponent(rbnFemale))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCellNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(chbShowPassword))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSAddrress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        // TODO add your handling code here:        
        String fName = txtFirstName.getText();

        if (fName.trim().equals("") || !InputValidation.isString(fName)) {
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtFirstName.setToolTipText("Plese enter your first name. Alphabet characters only.");
        } else {
            //txtFirstName.setBorder();
            txtFirstName.setBorder(tFieldBorder);
            txtFirstName.setToolTipText("Your First Name.");
        }
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtInitialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInitialFocusLost
        // TODO add your handling code here:
        String uIni = txtInitial.getText();

        if (uIni.trim().equals("") || !InputValidation.isString(uIni)) {
            txtInitial.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtInitial.setToolTipText("Please enter your initials. Alphabet characters only.");
        } else {
            //txtFirstName.setBorder();
            txtInitial.setBorder(tFieldBorder);
            txtInitial.setToolTipText("Your initials.");
        }
    }//GEN-LAST:event_txtInitialFocusLost

    private void txtStaffIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStaffIDFocusLost
        // TODO add your handling code here:
        String uID = txtStaffID.getText();

        if (uID.trim().equals("") || (uID.trim().length() != 13) || !InputValidation.isNumeric(uID)) {
            txtStaffID.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtStaffID.setToolTipText("Please enter your national ID.(13 Numerical Characters)");
        } else {
            //txtFirstName.setBorder();
            txtStaffID.setBorder(tFieldBorder);
            txtStaffID.setToolTipText("Your national ID.");
        }
    }//GEN-LAST:event_txtStaffIDFocusLost

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        // TODO add your handling code here:
        String iLName = txtLastName.getText();

        if (iLName.trim().equals("") || !InputValidation.isString(iLName)) {
            txtLastName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtLastName.setToolTipText("Please enter your last name. Alphabet characters only.");
        } else {
            //txtFirstName.setBorder();
            txtLastName.setBorder(tFieldBorder);
            txtLastName.setToolTipText("Your last name.");
        }
    }//GEN-LAST:event_txtLastNameFocusLost

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        try {
            // TODO add your handling code here:
            new LoginForm().setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtCellNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCellNumFocusLost
        // TODO add your handling code here:
        String uCNum = txtCellNum.getText();

        if (uCNum.trim().equals("") || (uCNum.trim().length() != 10) || !InputValidation.isNumeric(uCNum)) {
            txtCellNum.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtCellNum.setToolTipText("Please enter your cell number.(10 Numerical Characters)");
        } else {
            //txtFirstName.setBorder();
            txtCellNum.setBorder(tFieldBorder);
            txtCellNum.setToolTipText("Your cell number.");
        }
    }//GEN-LAST:event_txtCellNumFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        String uEmail = txtEmail.getText();

        if (uEmail.trim().equals("") || !InputValidation.isEmail(uEmail)) {
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtEmail.setToolTipText("Please enter your email address. eg. john.doe@gmail.co.za");
        } else {
            //txtFirstName.setBorder();
            txtEmail.setBorder(tFieldBorder);
            txtEmail.setToolTipText("Your email address.");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        char[] uPword = txtPassword.getPassword();

        if (uPword.length < 8) {
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtPassword.setToolTipText("Password should be at least 8 characters long.");
        } else {
            //txtFirstName.setBorder();
            txtPassword.setBorder(tFieldBorder);
            txtPassword.setToolTipText("Your password.");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtSAddrressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSAddrressFocusLost
        String uAddress = txtSAddrress.getText();

        if (uAddress.trim().equals("") || !InputValidation.isAlphaNum(uAddress)) {
            txtSAddrress.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtSAddrress.setToolTipText("Please enter your street address. eg. 123 Somewhere Rd.");
        } else {
            //txtFirstName.setBorder();
            txtSAddrress.setBorder(tFieldBorder);
            txtSAddrress.setToolTipText("Your street address");
        }
    }//GEN-LAST:event_txtSAddrressFocusLost

    private void cmbPositionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbPositionFocusLost

        if (cmbPosition.getSelectedIndex() == 0) {
            cmbPosition.setBackground(Color.red);
            //cmbPosition.setBorder(BorderFactory.createLineBorder(Color.RED));
            cmbPosition.setToolTipText("Please choose a valid position.");
        } else {
            //txtFirstName.setBorder();
            //cmbPosition.setBorder(cmbBorder);
            cmbPosition.setBackground(cmbBorder);
            cmbPosition.setToolTipText("Your position.");
        }

        if (cmbPosition.getSelectedItem().equals(position[2])) {
            if (cmbDepartment.isEnabled()) {
                cmbDepartment.setEnabled(false);
            }
        } else {
            if (!cmbDepartment.isEnabled()) {
                cmbDepartment.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cmbPositionFocusLost

    private void cmbCampusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbCampusFocusLost
        if (cmbCampus.getSelectedIndex() == 0) {
            //cmbCampus.setBorder(BorderFactory.createLineBorder(Color.RED));
            cmbCampus.setBackground(Color.RED);
            cmbCampus.setToolTipText("Please choose a valid campus.");
        } else {
            //txtFirstName.setBorder();
            //cmbCampus.setBorder(cmbBorder);
            cmbCampus.setBackground(cmbBorder);
            cmbCampus.setToolTipText("Your campus.");
        }
    }//GEN-LAST:event_cmbCampusFocusLost

    private void cmbDepartmentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbDepartmentFocusLost
        if (cmbDepartment.getSelectedIndex() == 0) {
            //cmbDepartment.setBorder(BorderFactory.createLineBorder(Color.RED));
            cmbDepartment.setBackground(Color.RED);
            cmbDepartment.setToolTipText("Please choose a valid department.");
        } else {
            //txtFirstName.setBorder();
            //cmbDepartment.setBorder(cmbBorder);
            cmbDepartment.setBackground(cmbBorder);
            cmbDepartment.setToolTipText("Your department.");
        }
    }//GEN-LAST:event_cmbDepartmentFocusLost

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try {
            //Validation

            String uID = txtStaffID.getText();
            String uFName = txtFirstName.getText();
            String uIni = txtInitial.getText();
            String uLName = txtLastName.getText();
            Date uDoB = dpkDoB.getDate();
            String uGender = "";
            String uCell = txtCellNum.getText();
            String uEmail = txtEmail.getText();
            char[] uPassword = txtPassword.getPassword();
            String uAddress = txtSAddrress.getText();

            //RADIOBUTTON VALIDATION
            if (!rbnFemale.isSelected() && !rbnMale.isSelected()) {
                JOptionPane.showMessageDialog(this, "Please select a gender", "Input Error", JOptionPane.ERROR_MESSAGE);
                rbnFemale.setFocusable(true);
                rbnFemale.requestFocus();
                return;
            } else if (rbnFemale.isSelected()) {
                uGender = "Female";
            } else {
                uGender = "Male";
            }

            //CMB Validation
            if (cmbPosition.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please select a position", "Input Error", JOptionPane.ERROR_MESSAGE);
                cmbPosition.setFocusable(true);
                cmbPosition.requestFocus();
                return;
            }
            if (cmbCampus.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please select a campus", "Input Error", JOptionPane.ERROR_MESSAGE);
                cmbCampus.setFocusable(true);
                cmbCampus.requestFocus();
                return;
            }
            if (cmbDepartment.isEnabled() && cmbDepartment.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please select a department", "Input Error", JOptionPane.ERROR_MESSAGE);
                cmbDepartment.setFocusable(true);
                cmbDepartment.requestFocus();
                return;
            }

            //STRING VALIDATION
            if (uID.trim().equals("") || uID.length() != 13 || !InputValidation.isNumeric(uID)) {
                JOptionPane.showMessageDialog(this, "Please input a valid ID.\nID should be 13 numerical characters.", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtStaffID.setFocusable(true);
                txtStaffID.requestFocus();
                return;
            }
            if (uFName.trim().equals("") || !InputValidation.isString(uFName)) {
                JOptionPane.showMessageDialog(this, "Please input a valid first name. Alphabet letters only.", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtFirstName.setFocusable(true);
                txtFirstName.requestFocus();
                return;
            }
            if (uIni.trim().equals("") || !InputValidation.isString(uIni)) {
                JOptionPane.showMessageDialog(this, "Please input a valid initial. Alphabet letters only.", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtInitial.setFocusable(true);
                txtInitial.requestFocus();
                return;
            }
            if (uLName.trim().equals("") || !InputValidation.isString(uLName)) {
                JOptionPane.showMessageDialog(this, "Please input a valid last name. Alphabet letters only.", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtLastName.setFocusable(true);
                txtLastName.requestFocus();
                return;
            }
            if (uCell.trim().equals("") || uCell.length() < 10 || !InputValidation.isNumeric(uCell)) {
                JOptionPane.showMessageDialog(this, "Please input a valid cell number.", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtCellNum.setFocusable(true);
                txtCellNum.requestFocus();
                return;
            }
            if (uEmail.trim().equals("") || !uEmail.contains("@")) {
                JOptionPane.showMessageDialog(this, "Please input a valid email address.", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtEmail.setFocusable(true);
                txtEmail.requestFocus();
                return;
            }
            if (uPassword.length < 8 || !InputValidation.isPassword(uPassword)) {
                JOptionPane.showMessageDialog(this, "Password should :\n• Be at least 8 characters.\n•"
                        + " Contain at least 1 special character.\n• Contain at least 1 numerical "
                        + "character.\n• Contain Uppercase and Lowercase letters.", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtPassword.setFocusable(true);
                txtPassword.requestFocus();
                return;
            }
            if (uAddress.trim().equals("") || !InputValidation.isAlphaNum(uAddress)) {
                JOptionPane.showMessageDialog(this, "Please input a valid address.", "Input Error", JOptionPane.ERROR_MESSAGE);
                txtSAddrress.setFocusable(true);
                txtSAddrress.requestFocus();
                return;
            }

            //REGISTER
            switch (cmbPosition.getSelectedIndex()) {
                case 1:
                    //STAFF
                    Staff nStaff = new Staff(cmbCampus.getSelectedIndex(), cmbDepartment.getSelectedIndex(), uID, uIni, uFName, uLName, uDoB, uGender, uCell, uEmail, uPassword, uAddress, "null");
                    String[] resultStaff = staff.registerStaff(nStaff);

                    if (resultStaff[0].equals("Success")) {
                        JOptionPane.showMessageDialog(this, "Registered Successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                        new LoginForm().setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, resultStaff[1], resultStaff[0], JOptionPane.ERROR_MESSAGE);
                    }

                    break;
                case 2:
                    //Admin
                    Admin nAdmin = new Admin(cmbCampus.getSelectedIndex(), uID, uIni, uFName, uLName, uDoB, uGender, uCell, uEmail, uPassword, uAddress, "null");
                    String[] resultAdmin = admin.registerAdmin(nAdmin);

                    if (resultAdmin[0].equals("Success")) {
                        JOptionPane.showMessageDialog(this, "Registered Successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                        new LoginForm().setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, resultAdmin[1], resultAdmin[0], JOptionPane.ERROR_MESSAGE);
                    }
                    break;
            }
        } catch (RemoteException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void chbShowPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbShowPasswordItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            txtPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chbShowPasswordItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistrationForm().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(RegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpGender;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox chbShowPassword;
    private javax.swing.JComboBox<String> cmbCampus;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbPosition;
    private org.jdesktop.swingx.JXDatePicker dpkDoB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JRadioButton rbnFemale;
    private javax.swing.JRadioButton rbnMale;
    private javax.swing.JTextField txtCellNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtInitial;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSAddrress;
    private javax.swing.JTextField txtStaffID;
    // End of variables declaration//GEN-END:variables
}
